name: "Auto-update packages"
on:
  schedule:
    # auto-update every day at 3:50 am
    - cron:  '50 3 * * *'
  workflow_dispatch:
  push:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
      with:
        ref: ci-auto-update
    - name: Install nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: drewrisinger
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: List NUR package attributes
      run: |
        nix-shell ./update-shell.nix --run 'nix eval --json "(import ./ci.nix { }).allAttrPaths" | jq . > nurAttrs.json'
        cat nurAttrs.json
    - name: Auto-update
      env:
        XDG_RUNTIME_DIR: ${{ github.workspace }}
        GIT_AUTHOR_NAME: Drew Risinger (bot)
        GIT_AUTHOR_EMAIL: drewrisinger@users.noreply.github.com
        GIT_COMMITTER_NAME: Drew Risinger (bot)
        GIT_COMMITTER_EMAIL: drewrisinger@users.noreply.github.com
      timeout-minutes: 30
      continue-on-error: true # want the PR to still submit even if some updates error
      run: nix-shell ./update-shell.nix --run "jq '.. | values | strings' nurAttrs.json | xargs -L1 nix-update --commit"
    - name: Submit auto-update PR
      uses: peter-evans/create-pull-request@v3
      # with:
      #   token: ${{ secrets.PAT }}
